FROM ubuntu:24.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates curl git jq gawk grep \
    bash tar gzip unzip xz-utils \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://go.dev/dl/go1.22.5.linux-amd64.tar.gz | tar -C /usr/local -xzf -
ENV PATH="/usr/local/go/bin:${PATH}"

RUN go install github.com/asdf-vm/asdf/cmd/asdf@v0.18.0
ENV PATH="/root/go/bin:${PATH}"

ENV ASDF_DIR=/root/.asdf
RUN mkdir -p "$ASDF_DIR"

RUN asdf plugin add sozo https://github.com/dojoengine/asdf-sozo.git || true
RUN asdf install sozo latest
RUN asdf set sozo latest

ENV PATH="/root/.asdf/shims:/root/.asdf/bin:${PATH}"

WORKDIR /app

COPY target/debug/saya /usr/local/bin/saya
COPY contracts /app/contracts

COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENV PRIVATE_KEY_KATANA0=0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912
ENV ADDRESS_KATANA0=0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec
ENV SETTLEMENT_RPC_URL=http://host.docker.internal:5050
ENV SALT=0x2
ENV CHAIN_ID=test-chain

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
