FROM ubuntu:24.04

RUN apt-get update && apt install -y tini

ARG TARGETPLATFORM

LABEL org.opencontainers.image.source=https://github.com/dojoengine/saya

COPY --from=binaries --chmod=755 $TARGETPLATFORM/saya /usr/local/bin/
COPY ./programs /programs

ENV SNOS_PROGRAM=/programs/snos.json
ENV LAYOUT_BRIDGE_PROGRAM=/programs/layout_bridge.json

ENTRYPOINT ["tini", "--"]
