on:
  push:
    branches:
      - "main"
  pull_request:

name: "build"

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v4"

      - name: "Setup Rust toolchain"
        uses: "dtolnay/rust-toolchain@master"
        with:
          toolchain: "1.89"

      - name: "Use Rust cache"
        uses: "Swatinem/rust-cache@v2"
        with:
          cache-on-failure: true

      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"

      - name: "Install dependencies"
        run: |
          pip install -r requirements.txt

      - name: "Cargo build (root workspace)"
        run: |
          cargo build --workspace --all-features

      - name: "Cargo build (bin/persistent)"
        working-directory: bin/persistent
        run: |
          cargo build --all-features

      - name: "Cargo build (bin/ops)"
        working-directory: bin/ops
        run: |
          cargo build --all-features

      - name: "Cargo build (bin/persistent-tee)"
        working-directory: bin/persistent-tee
        run: |
          cargo build --all-features
