on:
  push:
    branches:
      - "main"
  pull_request:

name: "Build"

jobs:
  build-programs:
    name: "Build and hash ${{ matrix.name }}"
    runs-on: "${{ matrix.runner }}"

    strategy:
      matrix:
        include:
          - name: "snos"
            runner: "ubuntu-latest-8-cores"
            script: "generate_snos.sh"
          - name: "layout_bridge"
            runner: "ubuntu-latest-16-cores"
            script: "generate_layout_bridge.sh"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v4"

      - name: "Build and hash program"
        run: |
          ./scripts/${{ matrix.script }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}.json
          path: ./programs/${{ matrix.name }}.json

  build-docker:
    name: "Build Docker image"
    runs-on: "ubuntu-latest"
    needs: build-programs

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v3"

      - name: Download snos.json
        uses: actions/download-artifact@v4
        with:
          name: snos.json
          path: ./programs/snos.json

      - name: Download layout_bridge.json
        uses: actions/download-artifact@v4
        with:
          name: layout_bridge.json
          path: ./programs/layout_bridge.json

      - name: "Build Docker image"
        run: |
          docker build .
