on:
  push:
    branches:
      - "main"
  pull_request:

name: "Build"

jobs:
  build-programs:
    uses: ./.github/workflows/build_programs.yml
    with:
      inherit-secrets: true

  build-docker:
    name: "Build Docker image"
    runs-on: "ubuntu-latest"
    needs: build-programs

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v3"

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: snos.json
          path: ./programs/snos.json

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: layout_bridge.json
          path: ./programs/snos.json

      - name: "Build Docker image"
        run: |
          docker build .
